### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by y-uchiida** [commew/timelogger-web#1]

**Comment by keitakn** [comment]
@y-uchiida 

おつかれさまです、こちらのissueですが粒度が大きいのでこちらで実装可能な粒度に分解させて頂きました。

こちらはクローズさせて頂きます。

- https://github.com/commew/timelogger-web/issues/2
- https://github.com/commew/timelogger-web/issues/3
- https://github.com/commew/timelogger-web/issues/4
- https://github.com/commew/timelogger-web/issues/5
- https://github.com/commew/timelogger-web/issues/6
- https://github.com/commew/timelogger-web/issues/7
- https://github.com/commew/timelogger-web/issues/8
- https://github.com/commew/timelogger-web/issues/9
- https://github.com/commew/timelogger-web/issues/10
- https://github.com/commew/timelogger-web/issues/11
- https://github.com/commew/timelogger-web/issues/13

**Comment by y-uchiida** [comment]
@keitakn 
@HaruyaFujimoto 
ありがとうございます！
タスクの設定と割り当ては、基本的に各チーム内で進めていただいて構いません🙇
こちらのタスクは藤本さんに用意してもらったやつだと思うので、分解した内容として過不足ないか、擦り合わせていただければ！

**Comment by y-uchiida** [comment]
@keitakn 
@HaruyaFujimoto 
あっ、すみません、フロントエンドとバックエンド、間違えてました🙇
フロントのissueは、タスクボードの表示確認のために僕が雑に追加したものでしたね...
フロントチームの方で進めてください👏

**Comment by keitakn** [comment]
@y-uchiida 承知しました、ご返答ありがとうございます。
