### ISSUE TITLE
タスクの計測開始・再開APIへのリクエストパラメータについて検討

### ISSUE THREAD

**Issue by kuniyuki-f** [commew/timelogger-web#119]
# 完了の定義

- [x] 掲題のリクエストパラメータである `startAt`の要不要を決定する
  - 不要の方向で固まりました！
- [x] 上記議論にて`startAt`が不要だと判断された場合、openapi.yamlから該当のパラメータ部分を削除する

# 補足情報

https://github.com/commew/timelogger-web/pull/115#discussion_r1320492081 のコメントでご指摘いただいていましたが、 @kuniyuki-f  が見逃していたため別のIssueを立てました🙏

**Comment by kuniyuki-f** [comment]
@keitakn @stkzk3110 
お疲れ様です！

下記の議論について、相談させていただきたいです🙏
お手隙でご確認いただき、ご意見いただければと思います！

# 議論
タスクの計測を開始・再開する時に、現在はフロントエンドから`startAt`というリクエストパラメータを送信しております！

- タスク記録開始API
https://timelogger-2vkuukkjv-commew.vercel.app/docs/api#/operations/postTasks
![image](https://github.com/commew/timelogger-web/assets/9443634/6fa1a565-39e0-4de1-9111-3fecba7f01eb)

- タスク記録再開API
https://timelogger-2vkuukkjv-commew.vercel.app/docs/api#/operations/patchTaskStartById
![image](https://github.com/commew/timelogger-web/assets/9443634/974036ba-5ca1-4ab5-a13a-f6692b7f0f19)

https://github.com/commew/timelogger-web/pull/115#discussion_r1320492081 で、以下のようなコメントをいただきました。
> startAtはこれは、フロントエンドで指定した値をバックエンドでそのまま保存するという想定でしょうか？
もしどうしてもそうしたいというのでなければ、不要じゃないかなと思います。
変更当時に見落していて申し訳ないのですが、タスク記録開始にもありますね。

個人的にはこちらの意見に賛成で、以下のようにコメントに返信しています。
> 自分も計測の開始時間みたいなアプリの状態についてはバックエンド側で管理する方が良いと思うので、startAtは不要かなと感じました！

みなさんのご意見も伺いたいです。
お手隙でご確認・コメントいただければ幸いです。
どうぞよろしくお願いいたします🙇

**Comment by keitakn** [comment]
@kuniyuki-f 

内容確認しました！自分もスルーしてしまってすいませんでした！

確かにおっしゃる通りサーバー側でデータを保持したほうが安定なので `startAt ` はなしの方向で大丈夫だと思います👍

**Comment by kuniyuki-f** [comment]
-  上記議論にてstartAtが不要だと判断された場合、openapi.yamlから該当のパラメータ部分を削除する

が完了したのでクローズします！
