### ISSUE TITLE
ページ内の見出しに適切な文言が入るように調整を行う

### ISSUE THREAD

**Issue by keitakn** [commew/timelogger-web#122]
# 完了の定義

- [ ] `/timer` ページで「Time Logger（仮）」という文言がFigmaのデザイン通り「計測」に変わっている事

# 補足情報

最悪ハードコードでも良いが `DefaultLayout` で `title` を受け取れるようにしておくのが無難。

**Comment by kuniyuki-f** [comment]
対応完了したのでクローズします！
