### ISSUE TITLE
仮置きしているMantineのロゴをFigma上の正式なロゴに変更する

### ISSUE THREAD

**Issue by keitakn** [commew/timelogger-web#125]
# 完了の定義

- [ ] タイトルの内容が実施されている事

# 補足情報

Figma上のこちらが正式ロゴなのでFigmaからエクスポートしてこちらを利用する。

<img width="593" alt="スクリーンショット 2023-09-12 23 22 52" src="https://github.com/commew/timelogger-web/assets/11032365/1bb0bc08-c147-4c6a-bed7-2a49e87462b6">

**Comment by kuniyuki-f** [comment]
対応完了したのでクローズします！
