### ISSUE TITLE
タスクの停止が常にid = 1のタスクに対して行われる

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-web#139]
# 概要

タスクの停止リクエストが常に`/tasks/1/stop`に対して行われます。

# 再現手順

1. タスク一覧を開く。
2. なんらかのタスクの「停止」ボタンを押す。

# このバグによって引き起こされる問題

想定するタスク以外のタスクが停止されたり、そもそもタスクが停止されずエラーになります。

# 補足情報

この辺見た感じ単純に未実装なのかもしれませんが、後で直すようなIssueもざっと見た感じないようなので一応ご報告します。

https://github.com/commew/timelogger-web/blob/11643e199201708bbd59af72e0495ce5ed919df9/src/components/TaskItem/TaskItem.tsx#L59

再開・終了もおそらく同様です。

**Comment by keitakn** [comment]
これはまだAPIをMockに対して行っている関係でそうなっています。

https://github.com/commew/timelogger-web/issues/77 で問題点は修正されますのでこちらはクローズしてもよいでしょうか？

**Comment by HAYASHI-Masayuki** [comment]
@keitakn ご確認ありがとうございます。
#77 で修正されるのであれば問題ありませんが、今回の箇所は`NEXT_PUBLIC_DEBUG_MOCK_API `とはあまり関係ない気がします。この環境変数を`'1'`に設定しても設定しなくても同様に問題が起きるので。
ということではなく、この辺のダミーになっている箇所もまとめて #77 で対応されるということであれば、このままクローズしていただいて大丈夫です！

**Comment by keitakn** [comment]
@HAYASHI-Masayuki 

>この環境変数を'1'に設定しても設定しなくても同様に問題が起きるので。

はい、それは認識しています、なので https://github.com/commew/timelogger-web/issues/77 の時に出た問題をissue化して個別に対応する予定でした。そういう意味だとこのissueは残しておいたほうが良いかもなのでやはりそのままで大丈夫です！

報告ありがとうございます。

ちなみに環境はどのあたりで出来そうでしょうか？

結合した時の問題点を早めに洗い出ししたく、11月になるとさらに時間を使えなさそうになるので早めにあるとありがたいです！

**Comment by HAYASHI-Masayuki** [comment]
@keitakn ありがとうございます、了解です！

> ちなみに環境はどのあたりで出来そうでしょうか？

すみません、こちらまだなんとも言えない状況です。今夜バックエンドチームでのMTがあるのでそのときに状況把握し、またお伝えします。

**Comment by HAYASHI-Masayuki** [comment]
あ、閉じてしまった。一応開き直しておきます……。

**Comment by kuniyuki-f** [comment]
@keitakn @HAYASHI-Masayuki 

お二人とも本イシューに関する議論ありがとうございます🙇

`TaskItem`のPropsに`taskId`を付与し、`TimerTemplate`から`taskId`渡すだけで解決できそうです。
（私が以前コーディングした時に対応漏れていましたね🙏💦）

Mock サーバのレスポンスデータを使っている間はどのみち`taskId = 1`固定なので、掲題の不具合は残ります。
しかし、バックエンドと疎通する際に発現するであろうバグを事前に修正できるので本イシューを先に対応しておくことは効果的だと思います。

したがって、この後PR作成しますので、またお手隙でご確認いただけますと幸いです！
（ローカルではすでに修正していますので、あとはリポジトリにアップするだけです！）

**Comment by keitakn** [comment]
@HAYASHI-Masayuki 

>すみません、こちらまだなんとも言えない状況です。今夜バックエンドチームでのMTがあるのでそのときに状況把握し、またお伝えします。

承知しました！

@kuniyuki-f 

https://github.com/commew/timelogger-web/issues/139#issuecomment-1762780204 進めて頂きありがとうございます👍

**Comment by HAYASHI-Masayuki** [comment]
@keitakn おつかれさまです。バックエンドの本番環境準備、申し訳ないですがまだかかりそうです。
繋ぎ込みで見つかるバグをできるだけ減らすために、私の方で手もとで動作確認して、できるだけバグを潰しておこうと思います。

**Comment by keitakn** [comment]
@HAYASHI-Masayuki 

承知しました、ありがとうございます！

ちなみにどのあたりで苦労されていますか？

https://github.com/commew/timelogger-api/issues/5#issuecomment-1749982899 あたりを見ると権限周りで詰まっていそうな印象を受けますが、バックエンドはRDBがPlanetSceleなのでもっと環境構築が簡単な `fly.io` などを使うのも手だと思いました。

基本無料で利用出来てかつ、Dockerfileを作るだけで動作します。

今からアーキテクチャ変えるほうがかえって時間かかるかもですが一応、自分が調べた時の記録を置いておきます。（自分のはPython + FastAPI + PlanetScaleでLLMの応答を返すAPIですが構築手順などは基本同じはずです）

- [fly.io にデプロイするまでの手順](https://zenn.dev/link/comments/b6ecfbc9a4b753)
- [設定ファイル（本番用）](https://github.com/nekochans/ai-cat-api/blob/main/fly.toml)
- [設定ファイル（ステージング用）](https://github.com/nekochans/ai-cat-api/blob/main/stg-fly.toml)
- [Dockerfile](https://github.com/nekochans/ai-cat-api/blob/main/Dockerfile)
- [ステージングデプロイワークフロー](https://github.com/nekochans/ai-cat-api/blob/main/.github/workflows/deploy-to-staging.yml)
- [本番デプロイワークフロー](https://github.com/nekochans/ai-cat-api/blob/main/.github/workflows/deploy-to-production.yml)

**Comment by HAYASHI-Masayuki** [comment]
@keitakn はい、仰る通り権限回りの問題が調査中という感じですね。
`fly.io`興味深いですね。場合によってはそちらも検討してみます。

@HaruyaFujimoto もし余裕あれば`fly.io`に移行する場合の工数ざっくり見てもらえると助かります。

**Comment by HAYASHI-Masayuki** [comment]
https://github.com/commew/timelogger-web/pull/140 で修正いただいたため、このIssueは閉じます。
