### ISSUE TITLE
タスクの表示内容がほかのタスクの内容と混ざることがある

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-web#141]
# 概要

1. タスクの記録開始後、別のカテゴリのタスクを記録開始すると、最初のタスクのカテゴリだけ上書きされて見えたり、
2. 停止中のタスクを開始(再開)すると、ほかの停止中のタスクの計測時間が開始したタスクと同じになったりします。

ほかにもおかしな挙動がありそうです。

# スクリーンショット、エラーメッセージ

1のパターンです。停止ボタンの効きが悪く見えたりするあたりも同じ原因っぽいです。
リロードして直るので、メモリ上の問題だとわかります。

https://github.com/commew/timelogger-web/assets/40618204/41d49096-6a88-4792-bcb8-3ef29ee6a822

# 補足情報

原因は`TaskItem`に渡している`key`がインデックスであるために、記録中と停止中で被りうるせいが一つです。
ただそれだけでなく、おそらく記録中・停止中タスクのデータの持ち方あたりにも問題があるようで、`key`だけ直しても完全には直らないようです。

**Comment by kuniyuki-f** [comment]
#145 で対応したので本イシューはクローズします！
