### ISSUE TITLE
レイアウトComponentの作成を行う

### ISSUE THREAD

**Issue by keitakn** [commew/timelogger-web#41]
# 完了の定義

- [x] レイアウト用のComponentが作成されている事
- [x] 上記レイアウト用Component内では [Figma](https://www.figma.com/file/Mowdr0KHcHfm2bmi7pfg75/UI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E8%B3%87%E6%96%99?node-id=0-1&t=v8B9eJgZ9P5OO4Ha-0) 上のHeaderComponentのデザインが利用されるようになっている事

<img width="785" alt="Layout" src="https://user-images.githubusercontent.com/11032365/230121605-aaff35dd-7a4f-46d0-82fd-e80a9c57d07c.png">

# 補足情報

このissue内では各リンクは機能していなくても問題ない。

このサービスはログイン前提のサービスなのでログアウト時の表示は作る必要がなさそう。

**Comment by stkzk3110** [comment]
Mantineのロゴを使用するため、以下をインストール。
@mantine/ds

依存関係で以下も必要そうなので合わせてインストール。
@tabler/icons-react

**Comment by stkzk3110** [comment]
対応完了したのでクローズします🙏
