### ISSUE TITLE
トップページの左カラムにカテゴリ名とグループ名を表示するComponentを追加する

### ISSUE THREAD

**Issue by keitakn** [commew/timelogger-web#42]
# 完了の定義

- [x] カテゴリ名とグループ名がトップページの左カラムに表示されている事
- [x] 上記に必要なComponentが実装されている事

<img width="781" alt="top" src="https://user-images.githubusercontent.com/11032365/230122252-2037c08e-52e4-40bc-97ac-126fca29311c.png">

# 補足情報

先に https://github.com/commew/timelogger-web/issues/41 を実施しておく。

**Comment by stkzk3110** [comment]
対応完了したのでクローズします🙏
