### ISSUE TITLE
ログアウト機能の実装を行う

### ISSUE THREAD

**Issue by keitakn** [commew/timelogger-web#43]
# 完了の定義

- [x] ログアウトが実行出来るようになっている事
- [x] ログアウト後はログインページに遷移するようになっている事

# 補足情報

初期リリース時に必須かと言われれば必須ではないが開発中にもログアウトが実装されていたほうが検証もしやすい + 実装コストも少ないので実装しておく。

**Comment by stkzk3110** [comment]
以下気になった部分。
別のIssue作ってやるが良さそう。
- ログインページではヘッダーナビゲーション、サイドバーは非表示にした方が良いかも。
- ログアウト状態だと自動でログインページに遷移するようにした方が良いかも。

<img width="1420" alt="スクリーンショット 2023-04-19 9 18 17" src="https://user-images.githubusercontent.com/36589062/232932692-3425476d-5a6c-4b2a-a3a7-f84e5fc6c4d4.png">

**Comment by keitakn** [comment]
@stkzk3110 https://github.com/commew/timelogger-web/issues/43#issuecomment-1513946050 ありがとうございます:pray:

新しく https://github.com/commew/timelogger-web/issues/62 を作成しました👍
