### ISSUE TITLE
計測を開始する機能を実装

### ISSUE THREAD

**Issue by c501306014** [commew/timelogger-web#47]
# 完了の定義

- [x] 左カラムのカテゴリ名にホバーしたら計測開始ボタンが表示されるようになっていること
![image](https://user-images.githubusercontent.com/9443634/230701713-e366d133-9108-47a8-a9bc-fa13097933de.png)
- [x] タスクホバーで表示された計測開始ボタンを押下すると、計測開始できるようになっていること
- [x] 計測開始時、サーバー側に計測データが正しく送信されるようになっていること

# 補足情報
- 計測開始前アラートについてはデザインチームが協議中のようです。
  - 本イシューでは実装なしで進めます。（別イシューで対応でも影響がないため）
    ![image](https://user-images.githubusercontent.com/9443634/230701749-b37216ee-8f67-4d91-83a5-4dae26d98171.png)
- 「記録中のタスク一覧」「停止中のタスク一覧」からも計測開始できるようなデザインになっています。
  しかし、本イシューとは別に以下のイシューを作成予定です。
  したがって、今回のイシューでは左カラムのカテゴリから計測開始できる機能のみ実装します。
    - 記録中のタスク一覧をトップページに表示する
    - 停止中のタスク一覧をトップページに表示する
  ![image](https://user-images.githubusercontent.com/9443634/230702007-35261429-64ce-4f46-93eb-b8a37b400a6c.png)

**Comment by y-uchiida** [comment]
@c501306014 
今更ながらご報告です...
計測開始時の確認モーダルの表示は無しでよいです！
左メニューの各カテゴリのボタンをクリックすると、すぐに計測が始まるようにしていただければと思います。

**Comment by c501306014** [comment]
@keitakn @stkzk3110 
#88 で対応したので、クローズします！
（ API 通信相手がモックだったり、レスポンスを計測中タスク一覧に追加・表示したりする実装はまだですが、また別のイシューで対応する、で良いと判断しました！）
