### ISSUE TITLE
デフォルトのカテゴリ、グループ名を返すAPIの設計を行う

### ISSUE THREAD

**Issue by keitakn** [commew/timelogger-web#49]
# 完了の定義

以下の条件を満たすAPIが設計され [public/docs/api/openapi.yaml](https://github.com/commew/timelogger-web/blob/main/public/docs/api/openapi.yaml) に内容が反映されている事

- [x] 初期状態で表示させるグループ名、カテゴリの一覧を返すAPIが実装されている事

具体的にどのような値を返すかは @y-uchiida さんに確認を行います。

**Comment by keitakn** [comment]
`swagger/v1/swagger.yaml` は仮でAPIのschemaはフロントエンド側で管理するとの事なので https://github.com/commew/timelogger-api からissueを移動させました。

**Comment by keitakn** [comment]
@y-uchiida こちらですがアカウント登録直後のユーザー向けに初期状態で表示させるカテゴリ、グループ名はどのようになるでしょうか？

こちらのissueにコメント頂けると幸いです！

**Comment by y-uchiida** [comment]
@keitakn 
グループとカテゴリの初期値についても、あすデザイナーチームと確認を取ります！

**Comment by y-uchiida** [comment]
以下の内容で、デザイナーチームと確認中です。確定まで少々お待ちください

| カテゴリグループ名称 | カテゴリ名称  |
|---|---|
| 仕事 | 会議 |
| 　　 | 資料作成 |
| 学習 | TOEIC |
| 趣味 | 散歩 |
| 　　 | 読書 |
| カテゴリグループなし | 移動・外出 |

**Comment by keitakn** [comment]
@y-uchiida 

ありがとうございます。

データ構造について確認です。

カテゴリグループ の配下に カテゴリが存在するという認識で間違いないでしょうか？
（カテゴリグループなしに関してもカテゴリグループなしというグループが存在している認識です）

**Comment by y-uchiida** [comment]
@keitakn 

>カテゴリグループ の配下に カテゴリが存在するという認識で間違いないでしょうか？
>（カテゴリグループなしに関してもカテゴリグループなしというグループが存在している認識です）

そのように考えていただいてよいです。  
プロトタイプの方では「（グループ未分類）」という名称になっていたので、こちらに合わせていただきたいです。

**Comment by y-uchiida** [comment]
@keitakn 

カテゴリとグループの初期値の件、デザイナーチームと合意取れました！
上記の内容で進めてください🙇

**Comment by keitakn** [comment]
@y-uchiida 承知しました！

# メモ（以下の内容がデフォルト値となる）

| カテゴリグループ名称 | カテゴリ名称  |
|---|---|
| 仕事 | 会議 |
| 　　 | 資料作成 |
| 学習 | TOEIC |
| 趣味 | 散歩 |
| 　　 | 読書 |
| グループ未分類 | 移動・外出 |

**Comment by stkzk3110** [comment]
📝 
TaskMeasurementCategoryGroup
TaskMeasurementCategory

**Comment by stkzk3110** [comment]
完了したのでクローズします。
