### ISSUE TITLE
計測を停止する機能を実装

### ISSUE THREAD

**Issue by kuniyuki-f** [commew/timelogger-web#53]
# 完了の定義

- [x] 記録中のタスクの停止ボタンを押下すると、計測を停止することができること
  ![image](https://user-images.githubusercontent.com/9443634/230715059-03aa0af6-bc69-4bd9-8256-69c52840b75a.png)
- [x] 計測停止時、サーバー側に計測データが正しく送信されるようになっていること
- [ ] デザインチームから確認が取れた場合、計測停止確認モーダルの実装も行う（オプション）

# 補足情報

- 本イシューではタスクの終了に関する処理は実装しない
- Figma上で「停止時のモーダルを表示するべきか否か」の判断が難しかったので、デザインチームに確認してから完了の定義を確定しようと思います。

**Comment by c501306014** [comment]
@keitakn 
お疲れ様です！
お忙しいところ恐れ入りますが、1点質問させていただきたいです🙏

- 設定用の歯車アイコンが表示されない
イシューをプロジェクトボードに追加しようと思いましたが、添付画像のように設定アイコンが表示されませんでした。
![image](https://user-images.githubusercontent.com/9443634/230716063-b7c835ac-4abc-41ad-be41-5a74b572402f.png)

私の方で何か設定を見落としている可能性がありますか？
あるいは、権限が足りないなどの問題が考えられますか？

お手数ですが、お手すきの際にご回答いただけると助かります🙇‍♂️

**Comment by keitakn** [comment]
@c501306014 

これは権限がないようですね、失礼しました:sweat_drops:

むちょこさんに権限の追加を依頼して頂いてよろしいでしょうか？

**Comment by keitakn** [comment]
モーダルの表示は必須ではないので https://github.com/commew/timelogger-web/issues/134 に分離してこちらはクローズします！
