### ISSUE TITLE
HeaderNavigationのuseStyles内のtypoの修正を実施する

### ISSUE THREAD

**Issue by keitakn** [commew/timelogger-web#55]
# 完了の定義

- [x] `borderButtom` の部分が `borderBottom` に修正されている事

# 補足情報

IDEで見た時に発見。

<img width="902" alt="スクリーンショット 2023-04-08 23 39 11" src="https://user-images.githubusercontent.com/11032365/230727158-de2a13f8-154d-4647-add8-580f8906c84d.png">

GitHub上のコードレビューだとtypoを見つけるのは以外と難しい。

`createStyles` の型定義を見たがCSSプロパティのコード補完は効くようになっているが存在しないCSSプロパティを入れてもBuildエラーにならないので発見が難しい。

もし余裕があれば型安全でstyleを書ける方法を検討してみる。

https://mantine.dev/styles/create-styles/

**Comment by stkzk3110** [comment]
完了したのでクローズします。
