### ISSUE TITLE
計測を終了する機能を実装

### ISSUE THREAD

**Issue by kuniyuki-f** [commew/timelogger-web#57]
# 完了の定義

- [x] 記録中または停止中のタスクの終了ボタンを押下すると、計測を終了できること
- [ ] 終了確認モーダルが実装されていること（オプション）
- [x] サーバー側に計測データが正しく送信されること
  
# 補足情報
- 計測を終了する機能＝タスクを保存する機能 の認識です。
したがって、「タスクの削除」については本イシューでは関心を持たないこととします。

**Comment by keitakn** [comment]
完了の定義の 終了確認モーダルが実装されていること（オプション） は必須ではないので https://github.com/commew/timelogger-web/issues/133 に分離しました！

よってこちらはクローズします！
