### ISSUE TITLE
記録中のタスク一覧を /timer に表示する

### ISSUE THREAD

**Issue by c501306014** [commew/timelogger-web#59]
# 完了の定義
- [x] 計測ページにステータスが「記録中」のタスクが表示されること
![image](https://user-images.githubusercontent.com/9443634/232444632-78006097-b7ec-41f4-bf2d-6a52b6575c8c.png)

# 補足情報
- 計測時間のデータはどのように扱うか検討が必要？決まっていたら補足ください。
  - 常にクライアント・サーバ間で同期するのか？　など
- 停止機能は #53 で対応
- 終了機能は #57 で対応
-  編集・削除機能の実装はイシュー未作成（2023/04/17現在）

**Comment by keitakn** [comment]
# メモ

@y-uchiida さんと話をした結果、計測を行うメインページのURLは `/timer` とする事にしたので、issueのタイトルを変更しました。

https://commew.slack.com/archives/C02JQQU4VLY/p1689090462619399?thread_ts=1689084655.940729&cid=C02JQQU4VLY

**Comment by c501306014** [comment]
#96 で対応したのでクローズします！
