### ISSUE TITLE
停止中のタスク一覧を /timer に表示する

### ISSUE THREAD

**Issue by c501306014** [commew/timelogger-web#60]
# 完了の定義

- [x]  計測ページにステータスが「停止中」のタスクが表示されること
![image](https://user-images.githubusercontent.com/9443634/232447003-c9056cd9-c9d3-433f-a85b-dde153fd2abd.png)

# 補足情報
- 開始機能は #47 で対応
- 終了機能は #57 で対応
-  編集・削除機能の実装はイシュー未作成（2023/04/17現在）

**Comment by keitakn** [comment]
# メモ

@y-uchiida さんと話をした結果、計測を行うメインページのURLは `/timer` とする事にしたので、issueのタイトルを変更しました。

https://commew.slack.com/archives/C02JQQU4VLY/p1689090462619399?thread_ts=1689084655.940729&cid=C02JQQU4VLY

**Comment by c501306014** [comment]
対応したのでクローズします！
