### ISSUE TITLE
タスクを停止状態から再開させる為のAPI設計を行う

### ISSUE THREAD

**Issue by keitakn** [commew/timelogger-web#79]
# 完了の定義

- [x] issueタイトルの条件を満たすAPIが設計されている事

本来は https://github.com/commew/timelogger-web/issues/52 の完了の定義に含めるべきだったが、抜けてしまっていたので新しくissueを追加。

# 補足情報

https://github.com/commew/timelogger-web/pull/74#pullrequestreview-1435363318 のコメントで必要性が発覚した。

**Comment by c501306014** [comment]
#115 で対応したのでクローズします。
レビューありがとうございましたー！
