### ISSUE TITLE
アカウント名は不要な気がする

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-web#83]
# 概要

アカウント登録APIを実装していて思ったのですが、アカウント名はなにを、いつ入れて、どこで使うものかがちょっとわかりません。デザインを確認しても、必要な箇所は今のところなさそうな感じでした。

必要性を検討したいです。その上で、必要であればいつどのように設定するのか決めて、不要であれば削除したいです。

# 再現手順

なし

# 再現環境

なし

# このバグによって引き起こされる問題

なし

# スクリーンショット、エラーメッセージ

なし

# 補足情報

https://github.com/commew/timelogger-web/blob/584e3ef17ef64dface7965777b32a74f71d26529/public/docs/api/openapi.yaml#L788-L790

**Comment by keitakn** [comment]
@HAYASHI-Masayuki デフォルトのJWTの形式でメールアドレス、名前、subが取れるので一応名前を登録しておくかくらいの温度感だったので `name` は削除してしまって問題ありません！

**Comment by HAYASHI-Masayuki** [comment]
@keitakn ありがとうございます！　それではAPI側から削除しておきます。フロントエンドの方の削除はお任せしてもよろしいでしょうか

**Comment by keitakn** [comment]
@HAYASHI-Masayuki 承知しました！

https://github.com/commew/timelogger-web/blob/main/public/docs/api/openapi.yaml の修正はこちらで対応します！

**Comment by HAYASHI-Masayuki** [comment]
@keitakn すみません、コード内にアカウント名が残っているようです。
https://github.com/commew/timelogger-web/blob/2d93a44a615c7b0381e36a8d63cf6778bede1e3b/src/features/account/account.ts#L22
こちらもご対応お願いいただけると助かります。

**Comment by keitakn** [comment]
@HAYASHI-Masayuki 

>https://github.com/commew/timelogger-web/issues/83#issuecomment-1684836159

申し訳ありません、以下のPRで対応しました！CIが通ったらマージします！

https://github.com/commew/timelogger-web/pull/107

**Comment by keitakn** [comment]
対応完了したのでクローズにします。

**Comment by HAYASHI-Masayuki** [comment]
@keitakn 素早い対応ありがとうございます！　ログインまでの動作問題ないこと確認しました。
その後タスク一覧の取得でAPIが未実装のため落ちますが、そちらは今後対応していきます。
