### ISSUE TITLE
トップに遷移した際に timelogger-lp の内容を表示させるように変更する

### ISSUE THREAD

**Issue by keitakn** [commew/timelogger-web#91]
# 完了の定義

- `/` に遷移した際に `timelogger-lp` の内容が表示されるように設定が変更されている事

# 補足情報

経緯は以下のスレッドを参照。

https://commew.slack.com/archives/C02JQQU4VLY/p1689084655940729

**Comment by y-uchiida** [comment]
PRマージされましたので、本issueをクローズします！🙇
